### ISSUE TITLE
Application Freezing When Loading Cards

### ISSUE THREAD

**Issue by FroggMaster** [finol-digital/Card-Game-Simulator#123]
**Describe the bug**
The application frequently freezes when loading images. If I have to load 5 cards on the screen, the entire application will show that it's not responding then. After about 1 - 2 minutes it will eventually load, this is even worse the more cards I attempt to view at once. 

This is causing me numerous issues when I begin attempting to play with someone. If we have to search our deck, the application will lock up and in some cases will drop a user from the game session. This causes them to lose all their progress, in some cases they can rejoin but do not see board pieces that had been previously placed. 

As the host when I went to search my deck, my application locked up and this shutdown the entire lobby. Also wiping the entirety of the board state. 

**To Reproduce**
1. Load large resolution images that are at least 1250 DPI (My Image resolution is 4055x5917) 
2. Attempt to view a deck of more than 200 cards. 
3. The application freezes for 1 - 2 minutes (sometimes longer) 
4. No error is presented. The application freezes. 

**Expected behavior**
I would expect to be able to view these images without any more than a 1 - 2 seconds delay. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A
 - Version v1.103

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser N/A
 - Version v1.103

**Additional context**
The problem occurs for both me and my friend who are attempting to use the application. We have different operating systems, but the experience is the same on both computers. When loading a card, or deck the entire application locks up and freezes.

**Comment by davidmfinol** [comment]
There should be a warning that pops up if your image sizes are >1MB.
Do you get an image sizes warning in CGS?

**Comment by FroggMaster** [comment]
I didn't get any warning about the image size, but I will try to downscale them and see if performance improves. Thanks for the quick reply. :)

**Comment by davidmfinol** [comment]
I've added some additional queuing that I think should resolve this issue.
I'm closing this issue, but please do add additional comments or re-open this issue if it persists.
