### ISSUE TITLE
Flipped/Masked Cards Contents Can Still Be Viewed

### ISSUE THREAD

**Issue by FroggMaster** [finol-digital/Card-Game-Simulator#124]
**Describe the bug**
When a card is flipped over another user is able to view the name and the card. 

**To Reproduce**
1. Load a deck of cards
2. Draw a card and place it face down 
3. Have another user hover over the card, they can see the name and double click the card to view the card. 

**Expected behavior**
When a card is flipped over I would expect only for the owner of the deck to be able to see the card name and contents.

**Comment by davidmfinol** [comment]
Depending on the game, some games may want all players to be able to view facedown cards.
This issue is a bit more nuanced, so it may take some time to implement correctly.

**Comment by FroggMaster** [comment]
Perhaps there could be a setting when creating a game to allow masking face down cards for anyone but the owner. Which would allow for the functionality to be toggle-able based on player requirements. 

In a TCG format sometimes you may want to avoid the other player knowing what you have on the board. I really appreciate you taking this into consideration as an enhancement. :) Thank you!

**Comment by DrVecctor** [comment]
I would really appreciate this feature too, it is strictly necessary for the game I would like to play.

**Comment by davidmfinol** [comment]
FYI: I'm planning to focus on resolving this issue in the next couple of weeks.

**Comment by davidmfinol** [comment]
Should be fixed in v1.118.

I'm closing this issue, but anyone please feel free to re-open/comment if I missed something.
