### ISSUE TITLE
Other Users Do Not See Rotated Card

### ISSUE THREAD

**Issue by FroggMaster** [finol-digital/Card-Game-Simulator#125]
**Describe the bug**
When rotating a card in a multiplayer lobby, other users do not see the card being rotated. 

**To Reproduce**
1. Place a card
2. Rotate that card
3. Ask if the other user is able to see if the card has been rotated. In my experience only the user whom rotated the card is able to see the card has been rotated. 

**Expected behavior**
I would expect the card state to be consistent for all users, if a card is rotated everyone should see this card has been rotated on the board.

**Comment by davidmfinol** [comment]
Thanks for the bug report!
I'll prioritize fixing this soon.
