### ISSUE TITLE
Ability to draw multiple cards to your hand. 

### ISSUE THREAD

**Issue by FroggMaster** [finol-digital/Card-Game-Simulator#126]
**Is your feature request related to a problem? Please describe.**
I would like to define a number of cards to draw to my hand. I could not find a way to do this within the existing application. 

**Describe the solution you'd like**
I would like to be able to right click on the card, then select Draw multiple cards. 
I should then be prompted to enter a number, so I can draw X cards. 

**Additional context**
This is useful for Trading Card Games that have card effects which cause you to draw 2 cards. 
This is useful for the start of game, when players need to draw 6+ cards to their hand.

**Comment by davidmfinol** [comment]
This is a good suggestion!
I've been thinking about adding something like this, so I'll be sure to add this to the roadmap now!

**Comment by davidmfinol** [comment]
I've added "Deal" and "Draw" buttons to the Card Drawer (along the bottom screen while in game-play).
The "Deal" button provides this functionality starting in v1.119, so I'm closing this issue.
Please comment/re-open if there is still any additional improvement needed after v1.119!
