### ISSUE TITLE
closing drawer makes cards in hand disappear

### ISSUE THREAD

**Issue by gitHu6-newb** [finol-digital/Card-Game-Simulator#131]
**Describe the bug**
cards in your Hand disappear even tho the number for cards in hand are still there.

**To Reproduce**
1. Put cards in your Hand.
2. Click on the '+' to open a new Drawer.
3. Click on the tab for your Hand to ensure you are still viewing your Hand.
4. X out a Drawer.
5. see error

**Expected behavior** 
For the Drawer to go away but any cards in Hand should still be there and visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version  123.0.6312.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
seems to work fine on Android pixel 6

**Additional context**
But on Win10 desktop chrome, seems like any tab (Hand or Drawer) that you are looking at, when you close some *other* Drawer (even if it's empty), the cards you're currently looking at will disappear with the number for how many cards were in there still remaining. I've tried minimizing/maximizing the Hand/Drawers, Adding/removing other tabs, and can't seem to bring them back.... this might be connected to a slightly different issue regarding drawers being crossed. Will make another report.

**Comment by davidmfinol** [comment]
Thanks for the bug report! I'll try to check on this soon.

**Comment by davidmfinol** [comment]
This should be fixed in v1.107 now
