### ISSUE TITLE
Images of cards within Hand/multiple Drawer tabs

### ISSUE THREAD

**Issue by gitHu6-newb** [finol-digital/Card-Game-Simulator#132]
**Describe the bug**
With cards in Hand and in multiple (2+) Drawer tabs, when closing one of the Drawer tabs other than the one immediately next to the Hand, the incorrect cards disappear and the count for how many cards in each tab gets messed up. 

**To Reproduce**
1. Put 1 card in Hand.
2. create Drawer and put 1 card in drawer (now called "drawer1")
3. Create another Drawer and put 2 cards in this drawer (now called "drawer2")
4. Make another Drawer and put 3 cards in this one (now called "drawer3")
5. Delete "drawer3" by clicking on the X for its Drawer.
6. see error in "drawer2" (somehow the cards from drawer3 have now replaced the cards of drawer2

**Expected behavior**
The Drawer with the correct cards to still be there.
Hand should have 1
Drawer1 should have 1
Drawer2 should still have 2
(Drawer3 was removed/closed out)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version  123.0.6312.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
seems to work fine on Android pixel 6

**Additional context**
seems like if all the open Drawer tabs were a linked list, that the game is always deleting the card images from an incorrect node of the list and propagating the images over, but handling the number of cards that's supposed to be in each tab correctly. I have only encountered this with a desktop pc's browser for playing in web mode. Using the phone app CGS seems to be fine.

**Comment by davidmfinol** [comment]
This should be fixed in v1.107 now
