### ISSUE TITLE
Can there only be 1 image for all cardbacks?

### ISSUE THREAD

**Issue by gitHu6-newb** [finol-digital/Card-Game-Simulator#133]
Awesome job making this! I'm having lots of fun playing with it. Is there a way to have more than one CardBack for different decks? As I understand it, the CardBackImageUrl is the only pic for a  cardback, and acts as a global back image for all cards. Is there, or can there be, a way to have another image for all cards of a certain SetId? 
Many thanks!

**Describe the solution you'd like**
To be able to see multiple decks on the table with different cardback pictures

**Describe alternatives you've considered**
i dunno, i'm a newb

**Additional context**

**Comment by davidmfinol** [comment]
Currently, only 1 card back is supported, but I do want to add support for more in the future!

**Comment by DrVecctor** [comment]
+1

**Comment by davidmfinol** [comment]
With v1.114, I'm adding initial support for different card backs.
I'll build out deeper support in an upcoming release.

**Comment by DrVecctor** [comment]
How does this initial support work? Do I have to edit any file (for a deck, for instance) to set the image file that should be used as back?

**Comment by davidmfinol** [comment]
It currently requires manually editing json files for your game in the CGS Games directory.
Documentation is available at https://www.cardgamesimulator.com/custom.html

To give an overview, though:
1) The card back images go into the `backs` folder
2) You have to declare cards in AllCards.json that use the back
3) You can have decks use the card with that back by placing the back id next to the card name in `<>` brackets (ie `1 Card Name <cardBackId>`)

**Comment by davidmfinol** [comment]
Targeting full rollout of this feature in v1.120:
- Game-Play: Support for card back faces
  - Select backs folder in Game Editor Menu
  - Select back from dropdown in Card Creator Menu
  - Search backs in Card Search/Filter Menu

**Comment by davidmfinol** [comment]
I ended up releasing a small unrelated change for the Grand Archive TCG in v1.120, so now the plan is to complete this feature in the next release, v1.121

**Comment by davidmfinol** [comment]
Released in v1.121:
- Game-Play: Support for card back faces
  - Select backs folder in Game Editor Menu
  - Select back from dropdown in Card Creator Menu and Set Import Menu
