### ISSUE TITLE
Avoid mirroring the playmat and cards while playing online

### ISSUE THREAD

**Issue by UserpvFreitas** [finol-digital/Card-Game-Simulator#138]
Hi! Keep this good work, man!
I have a request, if it is possible to build, off course.
I've been using Card-Game-Simulator, because I have to build a game related to logic thinking for my doctorate. 
The problem is, the concept behing playing against other player online is based on some other games like yugioh, magic, where it is ok to have the vision on player 1's side mirrowed.
But on my case, it will be pretty difficult to play if cards were not correct displayed like they're played. Is there a way to implement this?

Player 1 side
<img width="748" alt="image" src="https://github.com/finol-digital/Card-Game-Simulator/assets/72610198/c63b2343-d282-48b4-8fcc-081ca37c1008">

Player 2 side
<img width="535" alt="image" src="https://github.com/finol-digital/Card-Game-Simulator/assets/72610198/92becac7-5532-4626-9128-faa371446645">

What I want is, player 2 will see exact the same as player 1. If I play something on the left of the playmat, this will be displayed at left for player 2 too.

**Comment by davidmfinol** [comment]
Player 2 has their view rotated 180 degrees by default, but players can actually manually rotate their view.
Pressing the left or right arrow key will rotate 90 degrees in that direction: https://github.com/finol-digital/Card-Game-Simulator/wiki/Keyboard-Shortcuts-(Hotkeys)#play-mode
Does it work for you if player 2 presses left or right twice?

**Comment by UserpvFreitas** [comment]
David, you're a life saver!
This helped me a lot, tks!

**Comment by davidmfinol** [comment]
Glad it works for you!
I'm closing this issue, but please do let me know if you have any other issues.
