### ISSUE TITLE
FileBrowser from crosstales - Remove it immediately!

### ISSUE THREAD

**Issue by slaubenberger** [finol-digital/Card-Game-Simulator#41]
You are sharing our Tool "FileBrowser" in your repo.
This is not allowed, since it's a paid asset and not open-source:
https://assetstore.unity.com/packages/slug/98713?aid=1011lNGT

Remove it immediately or we have to issue a DMCA takedown of your repo!

**Comment by davidmfinol** [comment]
Sorry, it was not my intention to share proprietary code!
I've removed crosstales.FileBrowser from the repo!
I'm now using https://github.com/gkngkc/UnityStandaloneFileBrowser instead.

**Comment by slaubenberger** [comment]
Thank you!
