### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by Firensis** [finol-digital/Card-Game-Simulator#65]
Hello,
I found an article "[Why should Unity game developers use static analysis?](https://pvs-studio.com/en/blog/posts/csharp/0945/)" where an author checks your project using static analyzer. Perhaps, it will be interesting for you to see suspicious code fragments the analyzer found. Hope this will help you to make your code better :).

**Comment by davidmfinol** [comment]
Thats awesome, thanks for sharing!

I already use Rider and Sonar Cloud for code analysis, so I'm surprised they missed example 1. 
I've now fixed it, so thank you!

The other examples are found in plugin code from other open-source projects. 
Those code paths aren't even used by my app. 
However, I can't simply remove that code as that would require reworking the plugins in an unnecessary manner. 

I'll be closing this issue, but thanks again for sharing!
