### ISSUE TITLE
Unable to delete dice, tokens, or decks from play area

### ISSUE THREAD

**Issue by ZTenski2** [finol-digital/Card-Game-Simulator#91]
**Describe the bug**
In the android app, when selecting a dice, deck, or token in either single or multiplayer modes, tapping delete does not remove the item. I also tried dragging the item over delete as well, same behaviour. Once the button is tapped, the pulldown menu (with the dice +- and delete button) disappears but the item remains on the playing field. 

**To Reproduce**
1. Start a game with standard 52 card deck
2. Place a token on the field
3. Tap the token, and then tap delete

**Expected behavior**
The item should be removed from the playing field.

**Platform
 - OS: Android 13
 - hardware: Samsung s21 ultra
 - browser: iceraven 2.6.1
 - app version: Card Game Simulator 1.87.0 (play store)

**Additional context**
Great software, thank you for your efforts.

**Comment by davidmfinol** [comment]
Thanks for the bug report!
I though I had tested this, but it looks like I missed it.
I'll make sure to fix it for the next release.

**Comment by davidmfinol** [comment]
Releasing v1.88 now. Please let me know if it still doesn't work after updating to v1.88

**Comment by ZTenski2** [comment]
Works perfectly, thank you :)
