### ISSUE TITLE
Allow setting an exact value to a dice, for use as counters

### ISSUE THREAD

**Issue by ZTenski2** [finol-digital/Card-Game-Simulator#92]
FEATURE REQUEST

**Is your feature request related to a problem? Please describe.**
Some of the games I play need counters, like placing a dice set to 5 on the card to signify +5 to the card. In the current system, I need to set the dice by tapping + and - a bunch of times from whatever random value it rolled to when I created it, particularly with large numbers like 15 which would use larger dice or multiple dice in real life.

**Describe the solution you'd like**
Allow players to set a value to the dice, with either an entry box for typing or larger increments for the + - buttons when setting the dice (such as +5, +10, etc), so that they can be used as counters. Preferably, there would be a tickbox to disable rolling the dice (to prevent rolling by accident when double tapping in android, allthough this is optional since I could just turn that off in the settings menu), and also the value should be able to surpass the max value of the dice (for example, spawn a dice and set it to 15, regardless of the faces setting in the settings menu). This could also be done with a seperate game object, if going past the number of faces set in the settings menu is a problem. Negative numbers (or, alternatively, dice colors that can be set per-dice) would also be nice for delegating different kinds of counters, but don't want to ask for too much :)

**Describe alternatives you've considered**
Implementing counters seperately, spawning large numbers of tokens, or have "decks" of counters and simply search the deck when needed.

**Additional context**
Was just submitting a bug and thought I'd chip this in as well. I'll work around it for now though, I can still play with regular dice, just a bit more tedious :) . Love your app, excellent work. Thanks.

**Comment by davidmfinol** [comment]
Good suggestion! 
I'll look into adding this in the next couple of weeks.

**Comment by davidmfinol** [comment]
I'm adding a small input field next to the `-`, `+` , and `roll` buttons to allow manually entering a value for dice.

**Comment by davidmfinol** [comment]
Releasing v1.88 now. Please let me know if this doesn't work after updating to v1.88

**Comment by ZTenski2** [comment]
Excellent, thanks. Works exactly as expected, I will make good use of this :)
